apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.appName }}
  labels:
    app: {{ .Values.appName }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      containers:
        - name: {{ .Values.appName }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}

          # Static env vars
          env:
            {{- range .Values.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}


          env:
            {{- range .Values.env }}
              {{- if .value }}
              - name: {{ .name }}
                value: {{ .value | quote }}
              {{- else if .valueFrom }}
              - name: {{ .name }}
                valueFrom: 
                  {{ toYaml .valueFrom | indent 10 }}
              {{- end }}
            {{- end }}

            # ConfigMap envs
            {{- if .Values.configMap.enabled }}
            {{- range $key, $val := .Values.configMap.data }}
            - name: {{ $key }}
              valueFrom:
                configMapKeyRef:
                  name: {{ $.Values.configMap.name }}
                  key: {{ $key }}
            {{- end }}
            {{- end }}

          # Mount ExternalSecret as a file
          {{- if .Values.externalSecrets.enabled }}
          volumeMounts:
            - name: secret-volume
              mountPath: {{ .Values.externalSecrets.mountPath }}
              subPath: secrets.json
          {{- end }}

      # Volumes for ExternalSecret
      {{- if .Values.externalSecrets.enabled }}
      volumes:
        - name: secret-volume
          secret:
            secretName: {{ .Values.externalSecrets.targetName | default .Values.externalSecrets.secretName }}
            items:
              - key: {{ .Values.externalSecrets.remoteKey }}
                path: secrets.json
      {{- end }}

