apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: {{ .Values.appName }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ default .Values.service.port .Values.service.targetPort }}
  selector:
    app: {{ .Values.appName }}

